import { Tool, CategoryInfo, TagInfo, Category, Tag } from "./types";

export const categories: CategoryInfo[] = [
  { id: "frontend", name: "Frontend", description: "UI frameworks, styling, and client-side tools", icon: "Layout", color: "hsl(186 100% 50%)" },
  { id: "backend", name: "Backend", description: "Server frameworks, APIs, and runtime environments", icon: "Server", color: "hsl(280 100% 60%)" },
  { id: "devops", name: "DevOps", description: "Deployment, CI/CD, and infrastructure", icon: "Container", color: "hsl(45 100% 50%)" },
  { id: "ai-ml", name: "AI / ML", description: "Machine learning, LLMs, and AI tools", icon: "Brain", color: "hsl(320 100% 60%)" },
  { id: "database", name: "Database", description: "Databases, ORMs, and data management", icon: "Database", color: "hsl(150 80% 45%)" },
  { id: "testing", name: "Testing", description: "Testing frameworks and QA tools", icon: "TestTube", color: "hsl(30 100% 55%)" },
  { id: "mobile", name: "Mobile", description: "Mobile development frameworks", icon: "Smartphone", color: "hsl(200 100% 55%)" },
  { id: "security", name: "Security", description: "Security tools and practices", icon: "Shield", color: "hsl(0 80% 55%)" },
  { id: "productivity", name: "Productivity", description: "Developer productivity and workflow tools", icon: "Zap", color: "hsl(60 100% 50%)" },
];

export const tags: TagInfo[] = [
  { id: "open-source", name: "Open Source", color: "hsl(150 80% 45%)" },
  { id: "free", name: "Free", color: "hsl(186 100% 50%)" },
  { id: "freemium", name: "Freemium", color: "hsl(45 100% 50%)" },
  { id: "paid", name: "Paid", color: "hsl(280 100% 60%)" },
  { id: "self-hosted", name: "Self-Hosted", color: "hsl(30 100% 55%)" },
  { id: "cloud", name: "Cloud", color: "hsl(200 100% 55%)" },
  { id: "cli", name: "CLI", color: "hsl(0 0% 70%)" },
  { id: "gui", name: "GUI", color: "hsl(320 100% 60%)" },
  { id: "api", name: "API", color: "hsl(60 100% 50%)" },
  { id: "new", name: "New", color: "hsl(0 80% 55%)" },
];

export const tools: Tool[] = [
  // Frontend
  {
    id: "react",
    name: "React",
    description: "A JavaScript library for building user interfaces with declarative components.",
    longDescription: "React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://react.dev",
    githubUrl: "https://github.com/facebook/react",
    stars: 220000,
    upvotes: 1542,
    pros: ["Huge ecosystem", "Great documentation", "Strong community support"],
    cons: ["Learning curve for beginners", "Frequent updates"],
    alternatives: ["vue", "svelte", "solid"],
    createdAt: "2024-01-15",
  },
  {
    id: "vue",
    name: "Vue.js",
    description: "The progressive JavaScript framework for building modern web interfaces.",
    longDescription: "Vue is a progressive framework for building user interfaces. Unlike other monolithic frameworks, Vue is designed from the ground up to be incrementally adoptable.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://vuejs.org",
    githubUrl: "https://github.com/vuejs/vue",
    stars: 206000,
    upvotes: 1203,
    pros: ["Easy to learn", "Great documentation", "Flexible"],
    cons: ["Smaller ecosystem than React", "Less job opportunities"],
    alternatives: ["react", "svelte", "angular"],
    createdAt: "2024-01-10",
  },
  {
    id: "svelte",
    name: "Svelte",
    description: "Cybernetically enhanced web apps with a radical new approach to building UIs.",
    longDescription: "Svelte shifts the work from the browser to the compile step, resulting in highly optimized vanilla JavaScript at runtime with no framework overhead.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://svelte.dev",
    githubUrl: "https://github.com/sveltejs/svelte",
    stars: 75000,
    upvotes: 987,
    isNew: true,
    pros: ["No virtual DOM", "Smaller bundle sizes", "Easy to learn"],
    cons: ["Smaller ecosystem", "Fewer learning resources"],
    alternatives: ["react", "vue", "solid"],
    createdAt: "2024-02-01",
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    description: "A utility-first CSS framework for rapidly building custom designs.",
    longDescription: "Tailwind CSS is a highly customizable, low-level CSS framework that gives you all of the building blocks you need to build bespoke designs without any annoying opinionated styles you have to fight to override.",
    category: "frontend",
    tags: ["open-source", "free", "cli"],
    url: "https://tailwindcss.com",
    githubUrl: "https://github.com/tailwindlabs/tailwindcss",
    stars: 78000,
    upvotes: 1876,
    pros: ["Rapid development", "Highly customizable", "Great DX"],
    cons: ["HTML can get verbose", "Learning utility classes"],
    alternatives: ["bootstrap", "chakra-ui"],
    createdAt: "2024-01-05",
  },
  {
    id: "framer-motion",
    name: "Framer Motion",
    description: "Production-ready motion library for React with spring animations.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://www.framer.com/motion",
    githubUrl: "https://github.com/framer/motion",
    stars: 22000,
    upvotes: 654,
    pros: ["Declarative API", "Spring physics", "Gesture support"],
    cons: ["Bundle size", "React only"],
    createdAt: "2024-01-20",
  },
  {
    id: "shadcn-ui",
    name: "shadcn/ui",
    description: "Beautifully designed components built with Radix UI and Tailwind CSS.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://ui.shadcn.com",
    githubUrl: "https://github.com/shadcn/ui",
    stars: 55000,
    upvotes: 1432,
    isNew: true,
    pros: ["Copy-paste components", "Highly customizable", "Great accessibility"],
    cons: ["Not a package", "Manual updates"],
    createdAt: "2024-02-10",
  },
  // Backend
  {
    id: "nodejs",
    name: "Node.js",
    description: "JavaScript runtime built on Chrome's V8 engine for server-side applications.",
    category: "backend",
    tags: ["open-source", "free", "cli"],
    url: "https://nodejs.org",
    githubUrl: "https://github.com/nodejs/node",
    stars: 102000,
    upvotes: 1654,
    pros: ["Same language as frontend", "Huge ecosystem", "Fast"],
    cons: ["Callback hell", "Single-threaded"],
    createdAt: "2024-01-08",
  },
  {
    id: "deno",
    name: "Deno",
    description: "A modern runtime for JavaScript and TypeScript with security by default.",
    category: "backend",
    tags: ["open-source", "free", "cli"],
    url: "https://deno.land",
    githubUrl: "https://github.com/denoland/deno",
    stars: 92000,
    upvotes: 876,
    isNew: true,
    pros: ["TypeScript native", "Secure by default", "Modern tooling"],
    cons: ["Smaller ecosystem", "NPM compatibility issues"],
    createdAt: "2024-01-25",
  },
  {
    id: "bun",
    name: "Bun",
    description: "An incredibly fast JavaScript runtime, bundler, and package manager.",
    category: "backend",
    tags: ["open-source", "free", "cli"],
    url: "https://bun.sh",
    githubUrl: "https://github.com/oven-sh/bun",
    stars: 68000,
    upvotes: 1243,
    isNew: true,
    pros: ["Extremely fast", "All-in-one toolkit", "Node.js compatible"],
    cons: ["Still maturing", "Some compatibility issues"],
    createdAt: "2024-02-05",
  },
  {
    id: "trpc",
    name: "tRPC",
    description: "End-to-end typesafe APIs with TypeScript, no code generation needed.",
    category: "backend",
    tags: ["open-source", "free", "api"],
    url: "https://trpc.io",
    githubUrl: "https://github.com/trpc/trpc",
    stars: 31000,
    upvotes: 765,
    pros: ["Full type safety", "No code generation", "Great DX"],
    cons: ["TypeScript only", "Tight coupling"],
    createdAt: "2024-01-18",
  },
  {
    id: "hono",
    name: "Hono",
    description: "Ultrafast web framework for the Edges. Works on any runtime.",
    category: "backend",
    tags: ["open-source", "free", "api"],
    url: "https://hono.dev",
    githubUrl: "https://github.com/honojs/hono",
    stars: 14000,
    upvotes: 543,
    isNew: true,
    pros: ["Extremely fast", "Multi-runtime", "Lightweight"],
    cons: ["Smaller ecosystem", "Less middleware"],
    createdAt: "2024-02-15",
  },
  {
    id: "fastify",
    name: "Fastify",
    description: "Fast and low overhead web framework for Node.js with plugins architecture.",
    category: "backend",
    tags: ["open-source", "free", "api"],
    url: "https://fastify.dev",
    githubUrl: "https://github.com/fastify/fastify",
    stars: 30000,
    upvotes: 632,
    pros: ["Very fast", "Great plugin system", "JSON schema validation"],
    cons: ["Learning curve", "Different from Express"],
    createdAt: "2024-01-12",
  },
  // AI/ML
  {
    id: "langchain",
    name: "LangChain",
    description: "Framework for developing applications powered by language models.",
    category: "ai-ml",
    tags: ["open-source", "free", "api"],
    url: "https://langchain.com",
    githubUrl: "https://github.com/langchain-ai/langchain",
    stars: 78000,
    upvotes: 1432,
    pros: ["Comprehensive", "Great abstractions", "Active development"],
    cons: ["Complex", "Frequent breaking changes"],
    createdAt: "2024-01-22",
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "Get up and running with large language models locally.",
    category: "ai-ml",
    tags: ["open-source", "free", "self-hosted", "cli"],
    url: "https://ollama.ai",
    githubUrl: "https://github.com/ollama/ollama",
    stars: 52000,
    upvotes: 1876,
    isNew: true,
    pros: ["Run LLMs locally", "Easy to use", "No API costs"],
    cons: ["Hardware requirements", "Limited models"],
    createdAt: "2024-02-08",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "The AI community building the future with open source ML models.",
    category: "ai-ml",
    tags: ["open-source", "freemium", "api", "cloud"],
    url: "https://huggingface.co",
    githubUrl: "https://github.com/huggingface",
    stars: 120000,
    upvotes: 1654,
    pros: ["Massive model hub", "Great community", "Easy deployment"],
    cons: ["Can be expensive at scale", "Complex for beginners"],
    createdAt: "2024-01-06",
  },
  {
    id: "vercel-ai",
    name: "Vercel AI SDK",
    description: "Build AI-powered applications with React, Svelte, Vue, and Solid.",
    category: "ai-ml",
    tags: ["open-source", "free", "api"],
    url: "https://sdk.vercel.ai",
    githubUrl: "https://github.com/vercel/ai",
    stars: 7500,
    upvotes: 543,
    isNew: true,
    pros: ["Streaming support", "Multiple providers", "Easy integration"],
    cons: ["Vercel-focused", "Limited customization"],
    createdAt: "2024-02-12",
  },
  {
    id: "openai-api",
    name: "OpenAI API",
    description: "Access GPT-4, DALL-E, and other powerful AI models via API.",
    category: "ai-ml",
    tags: ["paid", "api", "cloud"],
    url: "https://platform.openai.com",
    upvotes: 2103,
    pros: ["State-of-the-art models", "Great documentation", "Reliable"],
    cons: ["Expensive at scale", "Rate limits", "No self-hosting"],
    createdAt: "2024-01-03",
  },
  // Database
  {
    id: "supabase",
    name: "Supabase",
    description: "The open source Firebase alternative with Postgres, Auth, and Realtime.",
    category: "database",
    tags: ["open-source", "freemium", "cloud", "self-hosted", "api"],
    url: "https://supabase.com",
    githubUrl: "https://github.com/supabase/supabase",
    stars: 64000,
    upvotes: 1987,
    pros: ["Postgres powered", "Great free tier", "Realtime subscriptions"],
    cons: ["Vendor lock-in risk", "Learning curve"],
    createdAt: "2024-01-14",
  },
  {
    id: "prisma",
    name: "Prisma",
    description: "Next-generation ORM for Node.js and TypeScript with type safety.",
    category: "database",
    tags: ["open-source", "free", "cli"],
    url: "https://prisma.io",
    githubUrl: "https://github.com/prisma/prisma",
    stars: 36000,
    upvotes: 1432,
    pros: ["Type safety", "Great migrations", "Intuitive schema"],
    cons: ["Performance overhead", "Complex queries"],
    createdAt: "2024-01-09",
  },
  {
    id: "drizzle",
    name: "Drizzle ORM",
    description: "TypeScript ORM that's lightweight, performant, and feels like SQL.",
    category: "database",
    tags: ["open-source", "free"],
    url: "https://orm.drizzle.team",
    githubUrl: "https://github.com/drizzle-team/drizzle-orm",
    stars: 19000,
    upvotes: 876,
    isNew: true,
    pros: ["SQL-like syntax", "Lightweight", "Great performance"],
    cons: ["Smaller ecosystem", "Less documentation"],
    createdAt: "2024-02-03",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    description: "The MySQL-compatible serverless database platform for modern apps.",
    category: "database",
    tags: ["freemium", "cloud", "api"],
    url: "https://planetscale.com",
    upvotes: 765,
    pros: ["Branching", "Serverless", "Great scaling"],
    cons: ["No foreign keys", "MySQL only"],
    createdAt: "2024-01-17",
  },
  {
    id: "neon",
    name: "Neon",
    description: "Serverless Postgres with branching, autoscaling, and bottomless storage.",
    category: "database",
    tags: ["freemium", "cloud", "api"],
    url: "https://neon.tech",
    stars: 11000,
    upvotes: 654,
    isNew: true,
    pros: ["Branching", "Serverless", "Great free tier"],
    cons: ["Cold starts", "Limited regions"],
    createdAt: "2024-02-07",
  },
  {
    id: "turso",
    name: "Turso",
    description: "SQLite for the edge. Distributed database with local-first sync.",
    category: "database",
    tags: ["freemium", "cloud", "self-hosted"],
    url: "https://turso.tech",
    githubUrl: "https://github.com/tursodatabase/libsql",
    stars: 8000,
    upvotes: 432,
    isNew: true,
    pros: ["Edge deployment", "SQLite compatible", "Fast reads"],
    cons: ["Write limitations", "New platform"],
    createdAt: "2024-02-14",
  },
  // DevOps
  {
    id: "docker",
    name: "Docker",
    description: "Platform for building, sharing, and running containerized applications.",
    category: "devops",
    tags: ["open-source", "freemium", "cli", "self-hosted"],
    url: "https://docker.com",
    githubUrl: "https://github.com/docker",
    stars: 68000,
    upvotes: 1876,
    pros: ["Industry standard", "Great ecosystem", "Portable"],
    cons: ["Resource heavy", "Learning curve"],
    createdAt: "2024-01-04",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description: "Container orchestration platform for automating deployment and scaling.",
    category: "devops",
    tags: ["open-source", "free", "cli", "self-hosted"],
    url: "https://kubernetes.io",
    githubUrl: "https://github.com/kubernetes/kubernetes",
    stars: 105000,
    upvotes: 1543,
    pros: ["Scalable", "Self-healing", "Industry standard"],
    cons: ["Complex", "Overkill for small projects"],
    createdAt: "2024-01-07",
  },
  {
    id: "terraform",
    name: "Terraform",
    description: "Infrastructure as code tool for building and managing cloud resources.",
    category: "devops",
    tags: ["open-source", "freemium", "cli"],
    url: "https://terraform.io",
    githubUrl: "https://github.com/hashicorp/terraform",
    stars: 40000,
    upvotes: 1234,
    pros: ["Multi-cloud", "Declarative", "Great community"],
    cons: ["State management", "HCL syntax"],
    createdAt: "2024-01-11",
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    description: "Automate workflows directly from your GitHub repository.",
    category: "devops",
    tags: ["freemium", "cloud"],
    url: "https://github.com/features/actions",
    upvotes: 1654,
    pros: ["Integrated with GitHub", "Great marketplace", "Free for public repos"],
    cons: ["Vendor lock-in", "YAML complexity"],
    createdAt: "2024-01-02",
  },
  {
    id: "railway",
    name: "Railway",
    description: "Deploy infrastructure, instantly. Build apps faster with instant deploys.",
    category: "devops",
    tags: ["freemium", "cloud"],
    url: "https://railway.app",
    upvotes: 876,
    isNew: true,
    pros: ["Simple deployment", "Great DX", "Fair pricing"],
    cons: ["Limited customization", "Smaller scale"],
    createdAt: "2024-02-09",
  },
  // Testing
  {
    id: "vitest",
    name: "Vitest",
    description: "Blazing fast unit test framework powered by Vite.",
    category: "testing",
    tags: ["open-source", "free", "cli"],
    url: "https://vitest.dev",
    githubUrl: "https://github.com/vitest-dev/vitest",
    stars: 11500,
    upvotes: 987,
    pros: ["Fast", "Vite-native", "Jest compatible"],
    cons: ["Newer", "Less plugins"],
    createdAt: "2024-01-19",
  },
  {
    id: "playwright",
    name: "Playwright",
    description: "End-to-end testing framework for modern web apps by Microsoft.",
    category: "testing",
    tags: ["open-source", "free", "cli"],
    url: "https://playwright.dev",
    githubUrl: "https://github.com/microsoft/playwright",
    stars: 59000,
    upvotes: 1432,
    pros: ["Multi-browser", "Great API", "Auto-waiting"],
    cons: ["Resource heavy", "Setup complexity"],
    createdAt: "2024-01-13",
  },
  {
    id: "cypress",
    name: "Cypress",
    description: "Fast, easy and reliable testing for anything that runs in a browser.",
    category: "testing",
    tags: ["open-source", "freemium", "cli", "gui"],
    url: "https://cypress.io",
    githubUrl: "https://github.com/cypress-io/cypress",
    stars: 46000,
    upvotes: 1234,
    pros: ["Great DX", "Time travel debugging", "Easy setup"],
    cons: ["Chrome-focused", "Slower than Playwright"],
    createdAt: "2024-01-16",
  },
  // Productivity
  {
    id: "cursor",
    name: "Cursor",
    description: "The AI-first code editor built for pair programming with AI.",
    category: "productivity",
    tags: ["freemium", "gui"],
    url: "https://cursor.com",
    upvotes: 2345,
    isNew: true,
    pros: ["AI-native", "VS Code base", "Context aware"],
    cons: ["Subscription cost", "Privacy concerns"],
    createdAt: "2024-02-11",
  },
  {
    id: "linear",
    name: "Linear",
    description: "The issue tracking tool designed for modern software teams.",
    category: "productivity",
    tags: ["freemium", "cloud", "gui"],
    url: "https://linear.app",
    upvotes: 1654,
    pros: ["Beautiful UI", "Fast", "Great keyboard shortcuts"],
    cons: ["Learning curve", "Limited free tier"],
    createdAt: "2024-01-21",
  },
  {
    id: "raycast",
    name: "Raycast",
    description: "A blazingly fast launcher and productivity tool for macOS.",
    category: "productivity",
    tags: ["freemium", "gui"],
    url: "https://raycast.com",
    upvotes: 1432,
    pros: ["Extensible", "Beautiful", "Developer-focused"],
    cons: ["macOS only", "Pro features expensive"],
    createdAt: "2024-01-23",
  },
  {
    id: "warp",
    name: "Warp",
    description: "The terminal reimagined with AI and collaborative features.",
    category: "productivity",
    tags: ["freemium", "gui", "cli"],
    url: "https://warp.dev",
    upvotes: 987,
    isNew: true,
    pros: ["AI assistance", "Modern UI", "Blocks"],
    cons: ["Account required", "Resource usage"],
    createdAt: "2024-02-06",
  },
];

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: Category): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolsByTag(tag: Tag): Tool[] {
  return tools.filter((tool) => tool.tags.includes(tag));
}

export function getNewTools(): Tool[] {
  return tools.filter((tool) => tool.isNew);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return tools.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.category.toLowerCase().includes(lowerQuery) ||
      tool.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}

export function getCategoryInfo(category: Category): CategoryInfo | undefined {
  return categories.find((c) => c.id === category);
}

export function getTagInfo(tag: Tag): TagInfo | undefined {
  return tags.find((t) => t.id === tag);
}
