import { Tool, CategoryInfo, TagInfo, Category, Tag } from "./types";

export const categories: CategoryInfo[] = [
  { id: "frontend", name: "Frontend", description: "UI frameworks, styling, and client-side tools", icon: "Layout", color: "hsl(186 100% 50%)" },
  { id: "backend", name: "Backend", description: "Server frameworks, APIs, and runtime environments", icon: "Server", color: "hsl(280 100% 60%)" },
  { id: "devops", name: "DevOps", description: "Deployment, CI/CD, and infrastructure", icon: "Container", color: "hsl(45 100% 50%)" },
  { id: "ai-ml", name: "AI / ML", description: "Machine learning, LLMs, and AI tools", icon: "Brain", color: "hsl(320 100% 60%)" },
  { id: "database", name: "Database", description: "Databases, ORMs, and data management", icon: "Database", color: "hsl(150 80% 45%)" },
  { id: "testing", name: "Testing", description: "Testing frameworks and QA tools", icon: "TestTube", color: "hsl(30 100% 55%)" },
  { id: "mobile", name: "Mobile", description: "Mobile development frameworks", icon: "Smartphone", color: "hsl(200 100% 55%)" },
  { id: "security", name: "Security", description: "Security tools and practices", icon: "Shield", color: "hsl(0 80% 55%)" },
  { id: "productivity", name: "Productivity", description: "Developer productivity and workflow tools", icon: "Zap", color: "hsl(60 100% 50%)" },
];

export const tags: TagInfo[] = [
  { id: "open-source", name: "Open Source", color: "hsl(150 80% 45%)" },
  { id: "free", name: "Free", color: "hsl(186 100% 50%)" },
  { id: "freemium", name: "Freemium", color: "hsl(45 100% 50%)" },
  { id: "paid", name: "Paid", color: "hsl(280 100% 60%)" },
  { id: "self-hosted", name: "Self-Hosted", color: "hsl(30 100% 55%)" },
  { id: "cloud", name: "Cloud", color: "hsl(200 100% 55%)" },
  { id: "cli", name: "CLI", color: "hsl(0 0% 70%)" },
  { id: "gui", name: "GUI", color: "hsl(320 100% 60%)" },
  { id: "api", name: "API", color: "hsl(60 100% 50%)" },
  { id: "new", name: "New", color: "hsl(0 80% 55%)" },
];

export const tools: Tool[] = [
  // Frontend
  {
    id: "react",
    name: "React",
    description: "A JavaScript library for building user interfaces with declarative components.",
    longDescription: "React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://react.dev",
    githubUrl: "https://github.com/facebook/react",
    stars: 220000,
    upvotes: 1542,
    pros: ["Huge ecosystem", "Great documentation", "Strong community support"],
    cons: ["Learning curve for beginners", "Frequent updates"],
    alternatives: ["vue", "svelte", "solid"],
    createdAt: "2024-01-15",
    useCases: ["Single-page applications", "Complex dashboards", "E-commerce platforms", "Real-time collaboration tools"],
    techStackFit: ["Next.js", "Vite", "TypeScript", "Redux", "TanStack Query"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "vue",
    name: "Vue.js",
    description: "The progressive JavaScript framework for building modern web interfaces.",
    longDescription: "Vue is a progressive framework for building user interfaces. Unlike other monolithic frameworks, Vue is designed from the ground up to be incrementally adoptable.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://vuejs.org",
    githubUrl: "https://github.com/vuejs/vue",
    stars: 206000,
    upvotes: 1203,
    pros: ["Easy to learn", "Great documentation", "Flexible"],
    cons: ["Smaller ecosystem than React", "Less job opportunities"],
    alternatives: ["react", "svelte", "angular"],
    createdAt: "2024-01-10",
    useCases: ["Progressive web apps", "Admin dashboards", "Content management systems", "Rapid prototyping"],
    techStackFit: ["Nuxt.js", "Vite", "Pinia", "TypeScript", "Vuetify"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "svelte",
    name: "Svelte",
    description: "Cybernetically enhanced web apps with a radical new approach to building UIs.",
    longDescription: "Svelte shifts the work from the browser to the compile step, resulting in highly optimized vanilla JavaScript at runtime with no framework overhead.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://svelte.dev",
    githubUrl: "https://github.com/sveltejs/svelte",
    stars: 75000,
    upvotes: 987,
    isNew: true,
    pros: ["No virtual DOM", "Smaller bundle sizes", "Easy to learn"],
    cons: ["Smaller ecosystem", "Fewer learning resources"],
    alternatives: ["react", "vue", "solid"],
    createdAt: "2024-02-01",
    useCases: ["Performance-critical apps", "Interactive data visualizations", "Lightweight embeddable widgets", "Static sites with SvelteKit"],
    techStackFit: ["SvelteKit", "TypeScript", "Vite", "TailwindCSS"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    description: "A utility-first CSS framework for rapidly building custom designs.",
    longDescription: "Tailwind CSS is a highly customizable, low-level CSS framework that gives you all of the building blocks you need to build bespoke designs without any annoying opinionated styles you have to fight to override.",
    category: "frontend",
    tags: ["open-source", "free", "cli"],
    url: "https://tailwindcss.com",
    githubUrl: "https://github.com/tailwindlabs/tailwindcss",
    stars: 78000,
    upvotes: 1876,
    pros: ["Rapid development", "Highly customizable", "Great DX"],
    cons: ["HTML can get verbose", "Learning utility classes"],
    alternatives: ["bootstrap", "chakra-ui"],
    createdAt: "2024-01-05",
    useCases: ["Rapid UI prototyping", "Design system implementation", "Component libraries", "Landing pages"],
    techStackFit: ["React", "Vue", "Next.js", "Vite", "shadcn/ui"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "framer-motion",
    name: "Framer Motion",
    description: "Production-ready motion library for React with spring animations.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://www.framer.com/motion",
    githubUrl: "https://github.com/framer/motion",
    stars: 22000,
    upvotes: 654,
    pros: ["Declarative API", "Spring physics", "Gesture support"],
    cons: ["Bundle size", "React only"],
    createdAt: "2024-01-20",
    useCases: ["Page transitions", "Micro-interactions", "Gesture-based UIs", "Animated data visualizations"],
    techStackFit: ["React", "Next.js", "Vite", "TypeScript"],
    learningCurve: "medium",
    communityActivity: "active",
  },
  {
    id: "shadcn-ui",
    name: "shadcn/ui",
    description: "Beautifully designed components built with Radix UI and Tailwind CSS.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://ui.shadcn.com",
    githubUrl: "https://github.com/shadcn/ui",
    stars: 55000,
    upvotes: 1432,
    isNew: true,
    pros: ["Copy-paste components", "Highly customizable", "Great accessibility"],
    cons: ["Not a package", "Manual updates"],
    createdAt: "2024-02-10",
    useCases: ["SaaS dashboards", "Admin panels", "Marketing sites", "Full-stack applications"],
    techStackFit: ["React", "Next.js", "Tailwind CSS", "TypeScript", "Radix UI"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  // Backend
  {
    id: "nodejs",
    name: "Node.js",
    description: "JavaScript runtime built on Chrome's V8 engine for server-side applications.",
    longDescription: "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. It allows developers to use JavaScript for server-side scripting, enabling full-stack development with a single language. Its non-blocking, event-driven architecture makes it ideal for scalable network applications.",
    category: "backend",
    tags: ["open-source", "free", "cli"],
    url: "https://nodejs.org",
    githubUrl: "https://github.com/nodejs/node",
    stars: 102000,
    upvotes: 1654,
    pros: ["Same language as frontend", "Huge ecosystem", "Fast"],
    cons: ["Callback hell", "Single-threaded"],
    createdAt: "2024-01-08",
    useCases: ["REST API servers", "Real-time applications", "Microservices", "CLI tools"],
    techStackFit: ["Express", "Fastify", "TypeScript", "MongoDB", "PostgreSQL", "Docker"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "deno",
    name: "Deno",
    description: "A modern runtime for JavaScript and TypeScript with security by default.",
    longDescription: "Deno is a modern runtime for JavaScript and TypeScript that uses V8 and is built in Rust. It provides secure defaults, native TypeScript support, and a decentralized module system that eliminates the need for package.json.",
    category: "backend",
    tags: ["open-source", "free", "cli"],
    url: "https://deno.land",
    githubUrl: "https://github.com/denoland/deno",
    stars: 92000,
    upvotes: 876,
    isNew: true,
    pros: ["TypeScript native", "Secure by default", "Modern tooling"],
    cons: ["Smaller ecosystem", "NPM compatibility issues"],
    createdAt: "2024-01-25",
    useCases: ["Edge functions", "Serverless APIs", "TypeScript-first projects", "Security-sensitive applications"],
    techStackFit: ["Fresh", "Oak", "TypeScript", "Supabase Edge", "Deno Deploy"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "bun",
    name: "Bun",
    description: "An incredibly fast JavaScript runtime, bundler, and package manager.",
    longDescription: "Bun is an all-in-one JavaScript runtime and toolkit designed for speed. It includes a bundler, transpiler, package manager, and test runner, all built from scratch in Zig for maximum performance.",
    category: "backend",
    tags: ["open-source", "free", "cli"],
    url: "https://bun.sh",
    githubUrl: "https://github.com/oven-sh/bun",
    stars: 68000,
    upvotes: 1243,
    isNew: true,
    pros: ["Extremely fast", "All-in-one toolkit", "Node.js compatible"],
    cons: ["Still maturing", "Some compatibility issues"],
    createdAt: "2024-02-05",
    useCases: ["High-performance APIs", "Build tooling replacement", "Script execution", "Monorepo management"],
    techStackFit: ["Elysia", "Hono", "TypeScript", "React", "Node.js ecosystem"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "trpc",
    name: "tRPC",
    description: "End-to-end typesafe APIs with TypeScript, no code generation needed.",
    longDescription: "tRPC allows you to easily build & consume fully typesafe APIs without schemas or code generation. It provides end-to-end type safety from your database to your frontend with zero runtime overhead.",
    category: "backend",
    tags: ["open-source", "free", "api"],
    url: "https://trpc.io",
    githubUrl: "https://github.com/trpc/trpc",
    stars: 31000,
    upvotes: 765,
    pros: ["Full type safety", "No code generation", "Great DX"],
    cons: ["TypeScript only", "Tight coupling"],
    createdAt: "2024-01-18",
    useCases: ["Full-stack TypeScript apps", "Internal APIs", "Rapid prototyping", "Type-safe mutations"],
    techStackFit: ["Next.js", "React", "TypeScript", "Prisma", "Zod"],
    learningCurve: "medium",
    communityActivity: "active",
  },
  {
    id: "hono",
    name: "Hono",
    description: "Ultrafast web framework for the Edges. Works on any runtime.",
    longDescription: "Hono is an ultrafast web framework for the Edge. It works on Cloudflare Workers, Deno, Bun, and Node.js. Built for speed with a tiny footprint, it provides Express-like routing with modern TypeScript support.",
    category: "backend",
    tags: ["open-source", "free", "api"],
    url: "https://hono.dev",
    githubUrl: "https://github.com/honojs/hono",
    stars: 14000,
    upvotes: 543,
    isNew: true,
    pros: ["Extremely fast", "Multi-runtime", "Lightweight"],
    cons: ["Smaller ecosystem", "Less middleware"],
    createdAt: "2024-02-15",
    useCases: ["Edge APIs", "Cloudflare Workers", "Lightweight microservices", "Serverless functions"],
    techStackFit: ["Cloudflare Workers", "Deno", "Bun", "TypeScript", "Zod"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "fastify",
    name: "Fastify",
    description: "Fast and low overhead web framework for Node.js with plugins architecture.",
    longDescription: "Fastify is a web framework highly focused on providing the best developer experience with the least overhead and a powerful plugin architecture. It's one of the fastest web frameworks in Node.js with full TypeScript support.",
    category: "backend",
    tags: ["open-source", "free", "api"],
    url: "https://fastify.dev",
    githubUrl: "https://github.com/fastify/fastify",
    stars: 30000,
    upvotes: 632,
    pros: ["Very fast", "Great plugin system", "JSON schema validation"],
    cons: ["Learning curve", "Different from Express"],
    createdAt: "2024-01-12",
    useCases: ["High-performance APIs", "Microservices", "REST APIs", "Plugin-based architectures"],
    techStackFit: ["Node.js", "TypeScript", "PostgreSQL", "MongoDB", "Docker"],
    learningCurve: "medium",
    communityActivity: "active",
  },
  // AI/ML
  {
    id: "langchain",
    name: "LangChain",
    description: "Framework for developing applications powered by language models.",
    longDescription: "LangChain is a framework for developing applications powered by language models. It provides abstractions for chains, agents, memory, and tools, making it easier to build complex AI applications that can reason and take actions.",
    category: "ai-ml",
    tags: ["open-source", "free", "api"],
    url: "https://langchain.com",
    githubUrl: "https://github.com/langchain-ai/langchain",
    stars: 78000,
    upvotes: 1432,
    pros: ["Comprehensive", "Great abstractions", "Active development"],
    cons: ["Complex", "Frequent breaking changes"],
    createdAt: "2024-01-22",
    useCases: ["RAG applications", "AI agents", "Chatbots", "Document Q&A systems"],
    techStackFit: ["OpenAI", "Pinecone", "Chroma", "Python", "TypeScript"],
    learningCurve: "high",
    communityActivity: "very-active",
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "Get up and running with large language models locally.",
    longDescription: "Ollama allows you to run large language models locally. It bundles model weights, configuration, and data into a single package, defined by a Modelfile. It supports Llama, Mistral, and other popular open-source models.",
    category: "ai-ml",
    tags: ["open-source", "free", "self-hosted", "cli"],
    url: "https://ollama.ai",
    githubUrl: "https://github.com/ollama/ollama",
    stars: 52000,
    upvotes: 1876,
    isNew: true,
    pros: ["Run LLMs locally", "Easy to use", "No API costs"],
    cons: ["Hardware requirements", "Limited models"],
    createdAt: "2024-02-08",
    useCases: ["Local AI development", "Privacy-focused applications", "Offline AI assistants", "Model experimentation"],
    techStackFit: ["LangChain", "Open WebUI", "Python", "Docker", "macOS/Linux"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "The AI community building the future with open source ML models.",
    longDescription: "Hugging Face is the AI community hub with thousands of pre-trained models and datasets. It provides the Transformers library, Inference API, and Spaces for deploying ML applications. The go-to platform for open-source AI.",
    category: "ai-ml",
    tags: ["open-source", "freemium", "api", "cloud"],
    url: "https://huggingface.co",
    githubUrl: "https://github.com/huggingface",
    stars: 120000,
    upvotes: 1654,
    pros: ["Massive model hub", "Great community", "Easy deployment"],
    cons: ["Can be expensive at scale", "Complex for beginners"],
    createdAt: "2024-01-06",
    useCases: ["Model hosting", "Fine-tuning", "NLP tasks", "Computer vision"],
    techStackFit: ["Transformers", "PyTorch", "TensorFlow", "Gradio", "Spaces"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "vercel-ai",
    name: "Vercel AI SDK",
    description: "Build AI-powered applications with React, Svelte, Vue, and Solid.",
    longDescription: "The Vercel AI SDK is the TypeScript toolkit designed to help developers build AI-powered applications with React, Svelte, Vue, and Solid. It provides hooks for streaming, tool calling, and structured outputs.",
    category: "ai-ml",
    tags: ["open-source", "free", "api"],
    url: "https://sdk.vercel.ai",
    githubUrl: "https://github.com/vercel/ai",
    stars: 7500,
    upvotes: 543,
    isNew: true,
    pros: ["Streaming support", "Multiple providers", "Easy integration"],
    cons: ["Vercel-focused", "Limited customization"],
    createdAt: "2024-02-12",
    useCases: ["Chat interfaces", "AI-powered forms", "Streaming responses", "Multi-provider apps"],
    techStackFit: ["Next.js", "React", "OpenAI", "Anthropic", "TypeScript"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "openai-api",
    name: "OpenAI API",
    description: "Access GPT-4, DALL-E, and other powerful AI models via API.",
    longDescription: "The OpenAI API provides access to GPT-4, DALL-E, Whisper, and other powerful AI models. It offers capabilities for text generation, code completion, image generation, speech-to-text, and more through a simple REST API.",
    category: "ai-ml",
    tags: ["paid", "api", "cloud"],
    url: "https://platform.openai.com",
    upvotes: 2103,
    pros: ["State-of-the-art models", "Great documentation", "Reliable"],
    cons: ["Expensive at scale", "Rate limits", "No self-hosting"],
    createdAt: "2024-01-03",
    useCases: ["Chatbots", "Content generation", "Code assistance", "Image generation"],
    techStackFit: ["LangChain", "Vercel AI SDK", "Python", "Node.js", "Any HTTP client"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  // Database
  {
    id: "supabase",
    name: "Supabase",
    description: "The open source Firebase alternative with Postgres, Auth, and Realtime.",
    longDescription: "Supabase is an open source Firebase alternative providing all the backend services you need. Start with a Postgres database, add authentication, instant APIs, edge functions, realtime subscriptions, and storage.",
    category: "database",
    tags: ["open-source", "freemium", "cloud", "self-hosted", "api"],
    url: "https://supabase.com",
    githubUrl: "https://github.com/supabase/supabase",
    stars: 64000,
    upvotes: 1987,
    pros: ["Postgres powered", "Great free tier", "Realtime subscriptions"],
    cons: ["Vendor lock-in risk", "Learning curve"],
    createdAt: "2024-01-14",
    useCases: ["Backend as a Service", "Real-time applications", "Authentication systems", "Serverless APIs"],
    techStackFit: ["React", "Next.js", "Vue", "PostgreSQL", "TypeScript", "Edge Functions"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "prisma",
    name: "Prisma",
    description: "Next-generation ORM for Node.js and TypeScript with type safety.",
    longDescription: "Prisma is a next-generation ORM that provides a type-safe database client, declarative data modeling, and automated migrations. It makes database access easy and helps prevent runtime errors.",
    category: "database",
    tags: ["open-source", "free", "cli"],
    url: "https://prisma.io",
    githubUrl: "https://github.com/prisma/prisma",
    stars: 36000,
    upvotes: 1432,
    pros: ["Type safety", "Great migrations", "Intuitive schema"],
    cons: ["Performance overhead", "Complex queries"],
    createdAt: "2024-01-09",
    useCases: ["Database migrations", "Type-safe queries", "Schema management", "Full-stack TypeScript apps"],
    techStackFit: ["Next.js", "Node.js", "TypeScript", "PostgreSQL", "MySQL", "MongoDB"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "drizzle",
    name: "Drizzle ORM",
    description: "TypeScript ORM that's lightweight, performant, and feels like SQL.",
    longDescription: "Drizzle ORM is a TypeScript ORM that feels like writing SQL. It's lightweight, performant, and provides full type safety. Unlike traditional ORMs, it doesn't hide the SQL from you.",
    category: "database",
    tags: ["open-source", "free"],
    url: "https://orm.drizzle.team",
    githubUrl: "https://github.com/drizzle-team/drizzle-orm",
    stars: 19000,
    upvotes: 876,
    isNew: true,
    pros: ["SQL-like syntax", "Lightweight", "Great performance"],
    cons: ["Smaller ecosystem", "Less documentation"],
    createdAt: "2024-02-03",
    useCases: ["SQL-first development", "High-performance apps", "Edge deployments", "Serverless"],
    techStackFit: ["Next.js", "Bun", "Node.js", "PostgreSQL", "SQLite", "MySQL"],
    learningCurve: "medium",
    communityActivity: "active",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    description: "The MySQL-compatible serverless database platform for modern apps.",
    longDescription: "PlanetScale is a MySQL-compatible serverless database platform with branching, non-blocking schema changes, and horizontal scaling. It's built on Vitess, which powers YouTube's databases.",
    category: "database",
    tags: ["freemium", "cloud", "api"],
    url: "https://planetscale.com",
    upvotes: 765,
    pros: ["Branching", "Serverless", "Great scaling"],
    cons: ["No foreign keys", "MySQL only"],
    createdAt: "2024-01-17",
    useCases: ["Scalable web apps", "Database branching workflows", "MySQL migrations", "High-traffic applications"],
    techStackFit: ["Prisma", "Drizzle", "Node.js", "Next.js", "MySQL clients"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "neon",
    name: "Neon",
    description: "Serverless Postgres with branching, autoscaling, and bottomless storage.",
    longDescription: "Neon is serverless Postgres with branching, autoscaling, and bottomless storage. It separates storage and compute, allowing databases to scale to zero and branch instantly for development workflows.",
    category: "database",
    tags: ["freemium", "cloud", "api"],
    url: "https://neon.tech",
    stars: 11000,
    upvotes: 654,
    isNew: true,
    pros: ["Branching", "Serverless", "Great free tier"],
    cons: ["Cold starts", "Limited regions"],
    createdAt: "2024-02-07",
    useCases: ["Serverless applications", "Database branching", "Preview environments", "Development databases"],
    techStackFit: ["Prisma", "Drizzle", "Next.js", "Vercel", "PostgreSQL clients"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "turso",
    name: "Turso",
    description: "SQLite for the edge. Distributed database with local-first sync.",
    longDescription: "Turso is SQLite for production. It provides edge-deployed SQLite databases with replication, enabling ultra-low latency reads from the edge while maintaining consistency. Built on libSQL, an open-source fork of SQLite.",
    category: "database",
    tags: ["freemium", "cloud", "self-hosted"],
    url: "https://turso.tech",
    githubUrl: "https://github.com/tursodatabase/libsql",
    stars: 8000,
    upvotes: 432,
    isNew: true,
    pros: ["Edge deployment", "SQLite compatible", "Fast reads"],
    cons: ["Write limitations", "New platform"],
    createdAt: "2024-02-14",
    useCases: ["Edge applications", "Local-first apps", "Embedded databases", "Read-heavy workloads"],
    techStackFit: ["Drizzle", "libSQL", "Bun", "Cloudflare Workers", "SQLite tools"],
    learningCurve: "low",
    communityActivity: "active",
  },
  // DevOps
  {
    id: "docker",
    name: "Docker",
    description: "Platform for building, sharing, and running containerized applications.",
    longDescription: "Docker is a platform for developing, shipping, and running applications in containers. It enables you to separate your applications from your infrastructure so you can deliver software quickly and consistently.",
    category: "devops",
    tags: ["open-source", "freemium", "cli", "self-hosted"],
    url: "https://docker.com",
    githubUrl: "https://github.com/docker",
    stars: 68000,
    upvotes: 1876,
    pros: ["Industry standard", "Great ecosystem", "Portable"],
    cons: ["Resource heavy", "Learning curve"],
    createdAt: "2024-01-04",
    useCases: ["Container development", "Microservices", "CI/CD pipelines", "Local development environments"],
    techStackFit: ["Kubernetes", "Docker Compose", "GitHub Actions", "Any language", "Linux"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description: "Container orchestration platform for automating deployment and scaling.",
    longDescription: "Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications. It groups containers into logical units for easy management and discovery.",
    category: "devops",
    tags: ["open-source", "free", "cli", "self-hosted"],
    url: "https://kubernetes.io",
    githubUrl: "https://github.com/kubernetes/kubernetes",
    stars: 105000,
    upvotes: 1543,
    pros: ["Scalable", "Self-healing", "Industry standard"],
    cons: ["Complex", "Overkill for small projects"],
    createdAt: "2024-01-07",
    useCases: ["Container orchestration", "Auto-scaling applications", "Service mesh", "Multi-cloud deployments"],
    techStackFit: ["Docker", "Helm", "Terraform", "Prometheus", "Istio"],
    learningCurve: "high",
    communityActivity: "very-active",
  },
  {
    id: "terraform",
    name: "Terraform",
    description: "Infrastructure as code tool for building and managing cloud resources.",
    longDescription: "Terraform is an infrastructure as code tool that lets you define and provision infrastructure using a declarative configuration language. It supports multiple cloud providers and enables version-controlled, repeatable infrastructure.",
    category: "devops",
    tags: ["open-source", "freemium", "cli"],
    url: "https://terraform.io",
    githubUrl: "https://github.com/hashicorp/terraform",
    stars: 40000,
    upvotes: 1234,
    pros: ["Multi-cloud", "Declarative", "Great community"],
    cons: ["State management", "HCL syntax"],
    createdAt: "2024-01-11",
    useCases: ["Infrastructure provisioning", "Multi-cloud management", "Environment templating", "GitOps workflows"],
    techStackFit: ["AWS", "GCP", "Azure", "Kubernetes", "GitHub Actions"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    description: "Automate workflows directly from your GitHub repository.",
    longDescription: "GitHub Actions is a CI/CD platform that allows you to automate your build, test, and deployment pipeline. You can create workflows that build and test every pull request or deploy merged code to production.",
    category: "devops",
    tags: ["freemium", "cloud"],
    url: "https://github.com/features/actions",
    upvotes: 1654,
    pros: ["Integrated with GitHub", "Great marketplace", "Free for public repos"],
    cons: ["Vendor lock-in", "YAML complexity"],
    createdAt: "2024-01-02",
    useCases: ["CI/CD pipelines", "Automated testing", "Deployment automation", "Issue management"],
    techStackFit: ["GitHub", "Docker", "Any language", "Cloud providers", "npm/pnpm"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "railway",
    name: "Railway",
    description: "Deploy infrastructure, instantly. Build apps faster with instant deploys.",
    longDescription: "Railway is a modern deployment platform that makes it easy to deploy applications. It provides instant deployments, database provisioning, and automatic SSL with a simple, developer-friendly interface.",
    category: "devops",
    tags: ["freemium", "cloud"],
    url: "https://railway.app",
    upvotes: 876,
    isNew: true,
    pros: ["Simple deployment", "Great DX", "Fair pricing"],
    cons: ["Limited customization", "Smaller scale"],
    createdAt: "2024-02-09",
    useCases: ["Quick deployments", "Hobby projects", "Startups", "Database hosting"],
    techStackFit: ["Node.js", "Python", "Go", "PostgreSQL", "Redis"],
    learningCurve: "low",
    communityActivity: "active",
  },
  // Testing
  {
    id: "vitest",
    name: "Vitest",
    description: "Blazing fast unit test framework powered by Vite.",
    longDescription: "Vitest is a blazing fast unit test framework powered by Vite. It provides Jest-compatible APIs with first-class TypeScript support and instant watch mode for rapid development feedback.",
    category: "testing",
    tags: ["open-source", "free", "cli"],
    url: "https://vitest.dev",
    githubUrl: "https://github.com/vitest-dev/vitest",
    stars: 11500,
    upvotes: 987,
    pros: ["Fast", "Vite-native", "Jest compatible"],
    cons: ["Newer", "Less plugins"],
    createdAt: "2024-01-19",
    useCases: ["Unit testing", "Component testing", "Integration testing", "Snapshot testing"],
    techStackFit: ["Vite", "React", "Vue", "TypeScript", "Vitest UI", "Testing Library"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "playwright",
    name: "Playwright",
    description: "End-to-end testing framework for modern web apps by Microsoft.",
    longDescription: "Playwright enables reliable end-to-end testing for modern web apps. It supports all major browsers and provides auto-wait, built-in assertions, and codegen for creating tests quickly.",
    category: "testing",
    tags: ["open-source", "free", "cli"],
    url: "https://playwright.dev",
    githubUrl: "https://github.com/microsoft/playwright",
    stars: 59000,
    upvotes: 1432,
    pros: ["Multi-browser", "Great API", "Auto-waiting"],
    cons: ["Resource heavy", "Setup complexity"],
    createdAt: "2024-01-13",
    useCases: ["E2E testing", "Visual regression testing", "API testing", "Cross-browser testing"],
    techStackFit: ["TypeScript", "GitHub Actions", "Docker", "Any web framework"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "cypress",
    name: "Cypress",
    description: "Fast, easy and reliable testing for anything that runs in a browser.",
    longDescription: "Cypress is a next-generation front-end testing tool built for the modern web. It provides time travel debugging, automatic waiting, and a rich interactive interface for running tests.",
    category: "testing",
    tags: ["open-source", "freemium", "cli", "gui"],
    url: "https://cypress.io",
    githubUrl: "https://github.com/cypress-io/cypress",
    stars: 46000,
    upvotes: 1234,
    pros: ["Great DX", "Time travel debugging", "Easy setup"],
    cons: ["Chrome-focused", "Slower than Playwright"],
    createdAt: "2024-01-16",
    useCases: ["E2E testing", "Component testing", "Visual testing", "API testing"],
    techStackFit: ["React", "Vue", "Angular", "TypeScript", "GitHub Actions"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  // Productivity
  {
    id: "cursor",
    name: "Cursor",
    description: "The AI-first code editor built for pair programming with AI.",
    longDescription: "Cursor is an AI-first code editor built for pair programming with AI. Based on VS Code, it provides deep AI integration with codebase understanding, inline editing, and chat-based assistance for faster development.",
    category: "productivity",
    tags: ["freemium", "gui"],
    url: "https://cursor.com",
    upvotes: 2345,
    isNew: true,
    pros: ["AI-native", "VS Code base", "Context aware"],
    cons: ["Subscription cost", "Privacy concerns"],
    createdAt: "2024-02-11",
    useCases: ["AI-assisted coding", "Code refactoring", "Learning new codebases", "Rapid prototyping"],
    techStackFit: ["Any language", "VS Code extensions", "Git", "Any framework"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "linear",
    name: "Linear",
    description: "The issue tracking tool designed for modern software teams.",
    longDescription: "Linear is an issue tracking and project management tool designed for modern software teams. It's known for its beautiful, fast interface and keyboard-first design that makes managing issues feel effortless.",
    category: "productivity",
    tags: ["freemium", "cloud", "gui"],
    url: "https://linear.app",
    upvotes: 1654,
    pros: ["Beautiful UI", "Fast", "Great keyboard shortcuts"],
    cons: ["Learning curve", "Limited free tier"],
    createdAt: "2024-01-21",
    useCases: ["Issue tracking", "Sprint planning", "Roadmap management", "Bug tracking"],
    techStackFit: ["GitHub", "Slack", "Figma", "Sentry", "Any development workflow"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "raycast",
    name: "Raycast",
    description: "A blazingly fast launcher and productivity tool for macOS.",
    longDescription: "Raycast is a blazingly fast, totally extendable launcher for macOS. It lets you control your tools with a few keystrokes, with built-in extensions for developers including snippets, window management, and clipboard history.",
    category: "productivity",
    tags: ["freemium", "gui"],
    url: "https://raycast.com",
    upvotes: 1432,
    pros: ["Extensible", "Beautiful", "Developer-focused"],
    cons: ["macOS only", "Pro features expensive"],
    createdAt: "2024-01-23",
    useCases: ["App launching", "Snippet management", "Window management", "Developer workflows"],
    techStackFit: ["macOS", "GitHub", "Jira", "Linear", "Any macOS app"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "warp",
    name: "Warp",
    description: "The terminal reimagined with AI and collaborative features.",
    longDescription: "Warp is a modern, Rust-based terminal with AI command search, blocks for organizing output, and collaborative features. It reimagines the terminal experience with a GPU-accelerated interface and modern UX patterns.",
    category: "productivity",
    tags: ["freemium", "gui", "cli"],
    url: "https://warp.dev",
    upvotes: 987,
    isNew: true,
    pros: ["AI assistance", "Modern UI", "Blocks"],
    cons: ["Account required", "Resource usage"],
    createdAt: "2024-02-06",
    useCases: ["Terminal workflows", "Command discovery", "Team collaboration", "AI-assisted commands"],
    techStackFit: ["Any CLI tools", "Git", "Docker", "SSH", "Any shell"],
    learningCurve: "low",
    communityActivity: "active",
  },
  // ─── New Additions (30 tools) ───

  // AI/ML - Latest Models & Tools
  {
    id: "opus-4-6",
    name: "Claude Opus 4.6",
    description: "Anthropic's most capable model with breakthrough agentic coding and extended thinking.",
    longDescription: "Claude Opus 4.6 is Anthropic's flagship model, featuring advanced reasoning, extended thinking capabilities, and best-in-class performance on agentic coding benchmarks. It excels at complex multi-step tasks and long-context understanding.",
    category: "ai-ml",
    tags: ["paid", "api", "cloud"],
    url: "https://www.anthropic.com",
    stars: 0,
    upvotes: 3210,
    isNew: true,
    pros: ["Top-tier reasoning", "Extended thinking", "Best agentic coding"],
    cons: ["Premium pricing", "Rate limits on launch"],
    createdAt: "2026-02-15",
    useCases: ["Complex code generation", "Multi-step reasoning", "Agentic workflows", "Research analysis"],
    techStackFit: ["Anthropic API", "LangChain", "Vercel AI SDK", "Python", "TypeScript"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "codex-5-3",
    name: "OpenAI Codex 5.3",
    description: "OpenAI's latest code-specialized model with autonomous software engineering capabilities.",
    longDescription: "Codex 5.3 represents OpenAI's most advanced code generation model, capable of autonomous multi-file refactoring, test generation, and full feature implementation with minimal guidance.",
    category: "ai-ml",
    tags: ["paid", "api", "cloud"],
    url: "https://platform.openai.com",
    upvotes: 2876,
    isNew: true,
    pros: ["Autonomous coding", "Multi-file understanding", "Test generation"],
    cons: ["Expensive for heavy usage", "Occasional hallucinations"],
    createdAt: "2026-02-10",
    useCases: ["Autonomous coding agents", "Code refactoring", "Test suite generation", "Legacy code migration"],
    techStackFit: ["OpenAI API", "GitHub Copilot", "VS Code", "Any language"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "gemini-3-pro",
    name: "Gemini 3 Pro",
    description: "Google's next-gen multimodal model with native image generation and reasoning.",
    longDescription: "Gemini 3 Pro delivers Google's most advanced multimodal capabilities with native image understanding and generation, complex reasoning, and a massive context window for processing large codebases.",
    category: "ai-ml",
    tags: ["freemium", "api", "cloud"],
    url: "https://ai.google.dev",
    upvotes: 2543,
    isNew: true,
    pros: ["Multimodal native", "Huge context window", "Image generation"],
    cons: ["Availability varies by region", "API changes frequently"],
    createdAt: "2026-02-05",
    useCases: ["Multimodal apps", "Document analysis", "Image understanding", "Code with visual context"],
    techStackFit: ["Google AI SDK", "Vercel AI SDK", "LangChain", "Python", "TypeScript"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "llama-4",
    name: "Llama 4",
    description: "Meta's open-weight foundation model with mixture-of-experts architecture.",
    longDescription: "Llama 4 is Meta's latest open-weight model featuring a mixture-of-experts architecture for efficient inference. It delivers competitive performance with GPT-5 class models while being fully self-hostable.",
    category: "ai-ml",
    tags: ["open-source", "free", "self-hosted"],
    url: "https://llama.meta.com",
    githubUrl: "https://github.com/meta-llama/llama",
    stars: 85000,
    upvotes: 2100,
    isNew: true,
    pros: ["Open weights", "Self-hostable", "MoE efficiency"],
    cons: ["Hardware requirements", "Fine-tuning complexity"],
    createdAt: "2026-01-20",
    useCases: ["Self-hosted AI", "Fine-tuning", "On-premise deployment", "Research"],
    techStackFit: ["Ollama", "vLLM", "Hugging Face", "PyTorch", "CUDA"],
    learningCurve: "high",
    communityActivity: "very-active",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    description: "Anthropic's agentic CLI tool for autonomous coding tasks in your terminal.",
    category: "ai-ml",
    tags: ["freemium", "cli"],
    url: "https://www.anthropic.com/claude-code",
    upvotes: 1876,
    isNew: true,
    pros: ["Terminal-native", "Git-aware", "Multi-file edits"],
    cons: ["API costs", "Requires Anthropic account"],
    createdAt: "2026-01-25",
    useCases: ["CLI-based coding", "Automated refactoring", "Bug fixing", "Code reviews"],
    techStackFit: ["Any language", "Git", "Terminal", "VS Code"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    description: "AI-powered IDE with deep codebase understanding and Cascade flows.",
    category: "productivity",
    tags: ["freemium", "gui"],
    url: "https://windsurf.com",
    upvotes: 1654,
    isNew: true,
    pros: ["Cascade multi-step flows", "Deep context", "VS Code compatible"],
    cons: ["Subscription required for pro", "Still maturing"],
    createdAt: "2026-01-15",
    useCases: ["AI pair programming", "Codebase exploration", "Automated workflows", "Rapid prototyping"],
    techStackFit: ["Any language", "VS Code extensions", "Git", "Any framework"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "v0",
    name: "v0 by Vercel",
    description: "AI-powered UI generation tool that creates React components from prompts.",
    category: "ai-ml",
    tags: ["freemium", "cloud", "gui"],
    url: "https://v0.dev",
    upvotes: 2345,
    isNew: true,
    pros: ["Instant UI generation", "shadcn/ui native", "Iterative refinement"],
    cons: ["React/Next.js focused", "Credits system"],
    createdAt: "2026-01-10",
    useCases: ["UI prototyping", "Component generation", "Landing pages", "Design to code"],
    techStackFit: ["React", "Next.js", "Tailwind CSS", "shadcn/ui", "TypeScript"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "bolt",
    name: "Bolt.new",
    description: "AI-powered full-stack app builder that runs entirely in the browser.",
    category: "ai-ml",
    tags: ["freemium", "cloud", "gui"],
    url: "https://bolt.new",
    upvotes: 1987,
    isNew: true,
    pros: ["Full-stack in browser", "Instant preview", "One-click deploy"],
    cons: ["Limited customization", "Token limits"],
    createdAt: "2026-01-05",
    useCases: ["Rapid prototyping", "MVP development", "Learning projects", "Quick demos"],
    techStackFit: ["React", "Vite", "Node.js", "Any framework"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "lovable",
    name: "Lovable",
    description: "AI-powered full-stack app development platform with real-time preview.",
    category: "ai-ml",
    tags: ["freemium", "cloud", "gui"],
    url: "https://lovable.dev",
    upvotes: 2654,
    isNew: true,
    pros: ["Full-stack generation", "Real-time preview", "Cloud backend included"],
    cons: ["Credit-based pricing", "React ecosystem only"],
    createdAt: "2026-02-01",
    useCases: ["Full-stack app development", "SaaS MVPs", "Dashboard creation", "Rapid prototyping"],
    techStackFit: ["React", "Vite", "Tailwind CSS", "TypeScript", "Supabase"],
    learningCurve: "low",
    communityActivity: "very-active",
  },

  // Frontend additions
  {
    id: "astro",
    name: "Astro",
    description: "The web framework for content-driven websites with zero JS by default.",
    longDescription: "Astro is a web framework that delivers lightning-fast performance by shipping zero JavaScript by default. It supports multiple UI frameworks and is ideal for content-heavy sites.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://astro.build",
    githubUrl: "https://github.com/withastro/astro",
    stars: 42000,
    upvotes: 1432,
    pros: ["Zero JS by default", "Multi-framework", "Island architecture"],
    cons: ["Not for SPAs", "Smaller ecosystem"],
    createdAt: "2025-12-01",
    useCases: ["Content sites", "Blogs", "Marketing pages", "Documentation"],
    techStackFit: ["React", "Vue", "Svelte", "Tailwind CSS", "MDX"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "solid-js",
    name: "SolidJS",
    description: "Reactive JavaScript library for building fast user interfaces without a virtual DOM.",
    category: "frontend",
    tags: ["open-source", "free"],
    url: "https://solidjs.com",
    githubUrl: "https://github.com/solidjs/solid",
    stars: 31000,
    upvotes: 876,
    pros: ["Fastest framework benchmarks", "Fine-grained reactivity", "Small bundle"],
    cons: ["Small ecosystem", "JSX differences from React"],
    createdAt: "2025-11-15",
    useCases: ["High-performance UIs", "Real-time dashboards", "Interactive widgets", "Embedded apps"],
    techStackFit: ["SolidStart", "Vite", "TypeScript", "Tailwind CSS"],
    learningCurve: "medium",
    communityActivity: "active",
  },

  // Backend additions
  {
    id: "elysiajs",
    name: "ElysiaJS",
    description: "Ergonomic TypeScript web framework built for Bun with end-to-end type safety.",
    category: "backend",
    tags: ["open-source", "free", "api"],
    url: "https://elysiajs.com",
    githubUrl: "https://github.com/elysiajs/elysia",
    stars: 9500,
    upvotes: 654,
    isNew: true,
    pros: ["Bun-native", "End-to-end types", "Extremely fast"],
    cons: ["Bun-only", "Small ecosystem"],
    createdAt: "2025-12-20",
    useCases: ["High-performance APIs", "Type-safe backends", "Bun projects", "Microservices"],
    techStackFit: ["Bun", "TypeScript", "Drizzle", "Eden Treaty"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "nitro",
    name: "Nitro",
    description: "Universal server engine powering Nuxt and H3 for any JavaScript runtime.",
    category: "backend",
    tags: ["open-source", "free"],
    url: "https://nitro.unjs.io",
    githubUrl: "https://github.com/unjs/nitro",
    stars: 5200,
    upvotes: 432,
    pros: ["Universal deployment", "File-based routing", "Auto-imports"],
    cons: ["Nuxt-centric docs", "Newer project"],
    createdAt: "2025-11-01",
    useCases: ["Server APIs", "Edge functions", "Universal server apps", "API routes"],
    techStackFit: ["Nuxt", "H3", "TypeScript", "Cloudflare", "Vercel"],
    learningCurve: "medium",
    communityActivity: "active",
  },

  // DevOps additions
  {
    id: "fly-io",
    name: "Fly.io",
    description: "Deploy app servers close to your users with global edge infrastructure.",
    category: "devops",
    tags: ["freemium", "cloud", "cli"],
    url: "https://fly.io",
    upvotes: 1100,
    pros: ["Global edge", "Great DX", "Generous free tier"],
    cons: ["Debugging complexity", "Smaller community"],
    createdAt: "2025-10-15",
    useCases: ["Edge deployments", "Global apps", "Database hosting", "Full-stack hosting"],
    techStackFit: ["Docker", "PostgreSQL", "Redis", "Any language"],
    learningCurve: "medium",
    communityActivity: "active",
  },
  {
    id: "coolify",
    name: "Coolify",
    description: "Open-source self-hostable alternative to Heroku, Netlify, and Vercel.",
    category: "devops",
    tags: ["open-source", "free", "self-hosted"],
    url: "https://coolify.io",
    githubUrl: "https://github.com/coollabsio/coolify",
    stars: 28000,
    upvotes: 1320,
    isNew: true,
    pros: ["Self-hosted", "No vendor lock-in", "Free"],
    cons: ["Requires own server", "Setup complexity"],
    createdAt: "2026-01-08",
    useCases: ["Self-hosted PaaS", "Docker deployments", "CI/CD", "Database management"],
    techStackFit: ["Docker", "Any language", "PostgreSQL", "Redis", "GitHub"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },

  // Database additions
  {
    id: "convex",
    name: "Convex",
    description: "Reactive backend-as-a-service with real-time sync and serverless functions.",
    category: "database",
    tags: ["freemium", "cloud", "api"],
    url: "https://convex.dev",
    githubUrl: "https://github.com/get-convex/convex-backend",
    stars: 4500,
    upvotes: 765,
    isNew: true,
    pros: ["Real-time by default", "TypeScript native", "No infrastructure management"],
    cons: ["Vendor lock-in", "Pricing at scale"],
    createdAt: "2026-01-12",
    useCases: ["Real-time apps", "Collaborative tools", "Chat apps", "Live dashboards"],
    techStackFit: ["React", "Next.js", "TypeScript", "Clerk"],
    learningCurve: "medium",
    communityActivity: "active",
  },
  {
    id: "upstash",
    name: "Upstash",
    description: "Serverless Redis and Kafka with per-request pricing for edge computing.",
    category: "database",
    tags: ["freemium", "cloud", "api"],
    url: "https://upstash.com",
    upvotes: 876,
    pros: ["Serverless", "Edge-compatible", "Pay-per-request"],
    cons: ["Redis limitations", "Cold starts"],
    createdAt: "2025-11-20",
    useCases: ["Rate limiting", "Session storage", "Caching", "Message queues"],
    techStackFit: ["Next.js", "Vercel", "Cloudflare Workers", "Any serverless"],
    learningCurve: "low",
    communityActivity: "active",
  },

  // Testing additions
  {
    id: "storybook",
    name: "Storybook",
    description: "Frontend workshop for building, documenting, and testing UI components.",
    category: "testing",
    tags: ["open-source", "free", "gui"],
    url: "https://storybook.js.org",
    githubUrl: "https://github.com/storybookjs/storybook",
    stars: 83000,
    upvotes: 1543,
    pros: ["Component isolation", "Great docs generation", "Visual testing"],
    cons: ["Setup overhead", "Build times"],
    createdAt: "2025-10-01",
    useCases: ["Component development", "Design systems", "Visual testing", "Documentation"],
    techStackFit: ["React", "Vue", "Angular", "Web Components", "Tailwind CSS"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "msw",
    name: "MSW",
    description: "API mocking library that intercepts requests at the network level.",
    category: "testing",
    tags: ["open-source", "free"],
    url: "https://mswjs.io",
    githubUrl: "https://github.com/mswjs/msw",
    stars: 15000,
    upvotes: 765,
    pros: ["Network-level mocking", "Works with any framework", "Service Worker based"],
    cons: ["Setup complexity", "Learning curve"],
    createdAt: "2025-10-15",
    useCases: ["API mocking", "Integration testing", "Development without backend", "E2E test fixtures"],
    techStackFit: ["Vitest", "Jest", "Playwright", "React", "Any framework"],
    learningCurve: "medium",
    communityActivity: "active",
  },

  // Security
  {
    id: "clerk",
    name: "Clerk",
    description: "Drop-in authentication and user management for modern applications.",
    category: "security",
    tags: ["freemium", "cloud", "api"],
    url: "https://clerk.com",
    upvotes: 1654,
    pros: ["Beautiful UI components", "Easy integration", "Great DX"],
    cons: ["Pricing at scale", "Vendor lock-in"],
    createdAt: "2025-12-10",
    useCases: ["Authentication", "User management", "Organization management", "SSO"],
    techStackFit: ["Next.js", "React", "Remix", "Convex", "TypeScript"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "better-auth",
    name: "Better Auth",
    description: "Framework-agnostic TypeScript auth library with a plugin ecosystem.",
    category: "security",
    tags: ["open-source", "free"],
    url: "https://better-auth.com",
    githubUrl: "https://github.com/better-auth/better-auth",
    stars: 6800,
    upvotes: 876,
    isNew: true,
    pros: ["Framework agnostic", "Plugin system", "Self-hosted"],
    cons: ["Newer project", "Smaller community"],
    createdAt: "2026-01-18",
    useCases: ["Self-hosted auth", "Multi-framework projects", "Custom auth flows", "Two-factor auth"],
    techStackFit: ["Any framework", "TypeScript", "Prisma", "Drizzle"],
    learningCurve: "medium",
    communityActivity: "active",
  },

  // Mobile
  {
    id: "expo",
    name: "Expo",
    description: "Platform for building universal React Native apps with ease.",
    category: "mobile",
    tags: ["open-source", "freemium", "cli"],
    url: "https://expo.dev",
    githubUrl: "https://github.com/expo/expo",
    stars: 30000,
    upvotes: 1432,
    pros: ["Easy setup", "OTA updates", "Great DX"],
    cons: ["Native module limitations", "Build times"],
    createdAt: "2025-11-05",
    useCases: ["Cross-platform mobile apps", "Rapid prototyping", "MVP development", "Universal apps"],
    techStackFit: ["React Native", "TypeScript", "Expo Router", "NativeWind"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },
  {
    id: "tauri",
    name: "Tauri",
    description: "Build smaller, faster, and more secure desktop and mobile apps with web tech.",
    category: "mobile",
    tags: ["open-source", "free", "cli"],
    url: "https://tauri.app",
    githubUrl: "https://github.com/tauri-apps/tauri",
    stars: 78000,
    upvotes: 1876,
    isNew: true,
    pros: ["Tiny bundles", "Rust backend", "Multi-platform"],
    cons: ["Rust knowledge helpful", "Smaller ecosystem"],
    createdAt: "2026-01-02",
    useCases: ["Desktop apps", "Cross-platform apps", "Lightweight alternatives to Electron", "Mobile apps"],
    techStackFit: ["React", "Vue", "Svelte", "Rust", "TypeScript"],
    learningCurve: "medium",
    communityActivity: "very-active",
  },

  // Productivity additions
  {
    id: "zed",
    name: "Zed",
    description: "High-performance code editor built in Rust with multiplayer collaboration.",
    category: "productivity",
    tags: ["open-source", "free", "gui"],
    url: "https://zed.dev",
    githubUrl: "https://github.com/zed-industries/zed",
    stars: 42000,
    upvotes: 1654,
    isNew: true,
    pros: ["Blazing fast", "Built-in collaboration", "AI assistant"],
    cons: ["Fewer extensions", "macOS/Linux only"],
    createdAt: "2026-01-22",
    useCases: ["Code editing", "Pair programming", "AI-assisted development", "Fast workflows"],
    techStackFit: ["Any language", "Git", "Tree-sitter", "LSP"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "fig",
    name: "Amazon Q (Fig)",
    description: "AI-powered terminal autocomplete and CLI tools by Amazon.",
    category: "productivity",
    tags: ["freemium", "cli"],
    url: "https://aws.amazon.com/q/developer/",
    upvotes: 987,
    pros: ["Terminal autocomplete", "AI assistance", "AWS integration"],
    cons: ["Amazon ecosystem focused", "Privacy concerns"],
    createdAt: "2025-12-15",
    useCases: ["Terminal productivity", "CLI autocomplete", "AWS workflows", "Command discovery"],
    techStackFit: ["Any shell", "AWS", "Git", "Docker", "kubectl"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "pieces",
    name: "Pieces for Developers",
    description: "AI-powered developer productivity tool for saving and reusing code snippets.",
    category: "productivity",
    tags: ["freemium", "gui"],
    url: "https://pieces.app",
    upvotes: 654,
    isNew: true,
    pros: ["Offline AI", "Cross-IDE", "Smart snippet management"],
    cons: ["Desktop app required", "Learning curve"],
    createdAt: "2026-02-01",
    useCases: ["Code snippet management", "Context switching", "Knowledge capture", "AI coding assistance"],
    techStackFit: ["VS Code", "JetBrains", "Chrome", "Any language"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "AI pair programmer that suggests code completions in real-time.",
    category: "productivity",
    tags: ["paid", "gui", "cloud"],
    url: "https://github.com/features/copilot",
    upvotes: 3100,
    pros: ["Deep IDE integration", "Multi-language", "Chat and inline suggestions"],
    cons: ["Subscription cost", "Code quality varies"],
    createdAt: "2025-09-01",
    useCases: ["Code completion", "Test generation", "Documentation", "Code translation"],
    techStackFit: ["VS Code", "JetBrains", "Neovim", "Any language", "Git"],
    learningCurve: "low",
    communityActivity: "very-active",
  },
  {
    id: "codeium",
    name: "Codeium",
    description: "Free AI-powered code completion and search for over 70 languages.",
    category: "productivity",
    tags: ["free", "gui", "cloud"],
    url: "https://codeium.com",
    upvotes: 1200,
    pros: ["Free tier", "Fast completions", "Wide language support"],
    cons: ["Less context-aware than Copilot", "Fewer features"],
    createdAt: "2025-10-01",
    useCases: ["Code completion", "Code search", "AI chat", "Refactoring suggestions"],
    techStackFit: ["VS Code", "JetBrains", "Vim", "Any language"],
    learningCurve: "low",
    communityActivity: "active",
  },
  {
    id: "biome",
    name: "Biome",
    description: "Fast formatter and linter for JavaScript, TypeScript, and more.",
    category: "productivity",
    tags: ["open-source", "free", "cli"],
    url: "https://biomejs.dev",
    githubUrl: "https://github.com/biomejs/biome",
    stars: 12000,
    upvotes: 987,
    isNew: true,
    pros: ["Extremely fast", "All-in-one", "ESLint/Prettier replacement"],
    cons: ["Fewer plugins", "Newer ecosystem"],
    createdAt: "2026-01-28",
    useCases: ["Code formatting", "Linting", "CI pipelines", "Monorepo tooling"],
    techStackFit: ["TypeScript", "React", "Any JS project", "CI/CD"],
    learningCurve: "low",
    communityActivity: "active",
  },
];

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: Category): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolsByTag(tag: Tag): Tool[] {
  return tools.filter((tool) => tool.tags.includes(tag));
}

export function getNewTools(): Tool[] {
  return tools.filter((tool) => tool.isNew);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return tools.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.category.toLowerCase().includes(lowerQuery) ||
      tool.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}

export function getCategoryInfo(category: Category): CategoryInfo | undefined {
  return categories.find((c) => c.id === category);
}

export function getTagInfo(tag: Tag): TagInfo | undefined {
  return tags.find((t) => t.id === tag);
}
